# Datos de tu base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_electrico
spring.datasource.username=root
spring.datasource.password=Ayrton02.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuraci\u00f3n de Hibernate (esto crea las tablas si no existen)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true