# Usamos la URL completa que Railway te da y le pegamos el "jdbc:" al principio
spring.datasource.url=jdbc:${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuraciones de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Esto le ayuda a Hibernate a saber que hablas con MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect